// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAsRkYNjfIDrr72rXTcCkkQ4is8TmwhQl8',
    appId: '1:1090663199673:web:9b059111375de72cdcfc68',
    messagingSenderId: '1090663199673',
    projectId: 'estoqueapp-69666034',
    authDomain: 'estoqueapp-69666034.firebaseapp.com',
    storageBucket: 'estoqueapp-69666034.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2DoDmYFw7C9fBKCyXIKDWnS0-uJxAwnU',
    appId: '1:1090663199673:android:ed21398eb6160ab8dcfc68',
    messagingSenderId: '1090663199673',
    projectId: 'estoqueapp-69666034',
    storageBucket: 'estoqueapp-69666034.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoIxgbFM1N7uRTDqiktJD8X390diCrils',
    appId: '1:1090663199673:ios:64199bc08593f12adcfc68',
    messagingSenderId: '1090663199673',
    projectId: 'estoqueapp-69666034',
    storageBucket: 'estoqueapp-69666034.firebasestorage.app',
    iosBundleId: 'com.example.clickCounter',
  );

}